> 10 questions
---
1. Create a ATM system that allows a user to perform the following
   operation :-
   • Check balance
   • Deposit money
   • Withdraw money
2. Create a number guessing game where user will guess the
   number and system check whether the winning number is correct
   or not (winning number will be hidden).
3. WAP to print Fibonacci series.
4. WAP to get the factorial of a number.
5. WAP to check whether the given string is palindrome or not.
6. WAP to check whether the number is prime or not.
7. WAP to print square of the even numbers and cube of the odd
   numbers in the range from 1 to 100.
8. WAP to print the square of each numbers in a list using map
   function.
9. WAP to print Diamond pattern.
10. Create a class of student with the attributes.
---
> # 50 Questions
1. Write a Python program to print "Hello, World!" in interactive mode.
2. Write a b that takes user input for their name and prints a greeting.
3. Create a program that demonstrates the use of variables by assigning and printing different data types (e.g., integer, float, string).
4. Write a script that takes two numbers as input and prints their sum.
5. Write a program that uses arithmetic operators to perform basic math operations on two user-input numbers.
6. Create a Python script that uses at least three different types of literals (e.g., string, integer, float).
7. Write a Python script to demonstrate the use of assignment operators.
8. Write a program that checks if a given word is a Python keyword.
9. Create a program that reads an integer from the user and prints whether it's positive,negative, or zero.
10. Write a program that takes a number as input, converts it to a string, and displays it with a message.
11. Write a program to demonstrate the usage of various data types in Python (int, float, bool, string).
12. Write a script that stores and prints a list of favorite colors.
13. Create a program that creates a tuple of 5 numbers and prints the sum of the numbers.
14. Write a program to convert a list into a set and print the result.
15. Create a dictionary to store student names as keys and their scores as values. Print the dictionary.
16. Write a program that demonstrates the immutability of tuples.
17. Create a program that adds two lists element-wise and stores the result in a new list.
18. Write a program that accepts user input as a set and performs union and intersection with a predefined set.
19. Write a Python program to take a string as input and print each character on a new line.
20. Create a program that uses string slicing to reverse a given string.
21. Write a script that takes a sentence as input and prints the sentence in all uppercase letters.
22. Write a program that counts the number of vowels in a given string.
23. Create a program that concatenates two strings and prints the result.
24. Write a program to create a list of integers, then print the maximum and minimum values.
25. Write a script to join two lists and print the combined list.
26. Create a program to replicate a list three times and print the result.
27. Write a program that takes a list of numbers as input and prints only the even numbers.
28. Write a program that creates a tuple of 5 strings and accesses the second element.
29. Create a program that joins two tuples and prints the result.
30. Write a script that replicates a tuple twice and prints the result.
31. Write a program that creates a dictionary with three key-value pairs and prints all the keys.
32. Create a Python program that creates a set of numbers and prints it.
33. Write a program to convert a list into a frozenset and print it.
34. Write a program to demonstrate the use of a set operation (union or intersection) with two sets.
35. Write a program that uses an `if-else` statement to check if a given number is even or odd.
36. Create a Pandas DataFrame with columns "Name", "Age", and "Score" using sample data. Display the first 5 rows.
37. Load a CSV file into a Pandas DataFrame and print the summary statistics of its numerical columns.
38. Write a program that filters rows in a DataFrame based on a specific condition (e.g., all rows where Age > 20).
39. Create a 3x3 NumPy array with random integers and calculate its transpose.
40. Write a program to create a 1D NumPy array of values from 0 to 10, then replace all even values with -1.
41. Using a NumPy array, calculate the mean, median, and standard deviation of the values.
42. Create a Python class called Rectangle with attributes for length and width, and a method to calculate the area of the rectangle.
43. Write a Python class BankAccount with methods to deposit, withdraw, and check the balance. Ensure that withdrawals cannot exceed the     balance.
44. Create an Employee class with name and salary attributes, and a method to give a raise.Demonstrate how to use inheritance                by creating a Manager subclass.
45. Write a Python script to read a text file line by line and count the number of lines in the file.
46. Write a program that appends text to an existing file without overwriting its current content.
47. Create a script to read a CSV file and print each row in a formatted way.
48. Write a program that asks for two numbers as input and divides the first by the second. Handle any exceptions that may occur (e.g.,      ZeroDivisionError, ValueError).
49. Create a function that reads from a file. Handle the FileNotFoundError exception if the file does not exist.
50. Write a script that asks the user for a number and calculates its square root. Handle cases where the input is not a number or is        negative.

In [1]:
# 2. number guessing
import random

# Generate a random number between 1 and 200
number = random.randint(1, 200)

while True:
    try:
        # Prompt user for input
        user_guess = int(input("Enter a number to guess: "))

        # Check conditions
        if user_guess < number // 2:
            print("Too low")
        elif user_guess < number:
            print("Low")
        elif user_guess > number * 2:
            print("Too high")
        elif user_guess > number:
            print("High")
        elif user_guess == number:
            print("Matched! You guessed it!")
            break  # Exit the loop when guessed correctly
    except ValueError:
        # Handle invalid input (non-integer values)
        print("Invalid input! Please enter an integer.")
        


Enter a number to guess:  44


Too low


Enter a number to guess:  88


Low


Enter a number to guess:  100


Low


Enter a number to guess:  111


Low


Enter a number to guess:  117


Low


Enter a number to guess:  144


Low


Enter a number to guess:  178


High


Enter a number to guess:  155


High


Enter a number to guess:  150


Low


Enter a number to guess:  153


Low


Enter a number to guess:  154


Matched! You guessed it!


In [1]:
#3. fibonacci series
def fib(number):
    if number <=1:
        return number
    else:
        return fib(number-1) + fib(number-2)
number=int(input("enter the number for series:"))
for i in range(number):
    print(fib(i),end=" ")



enter the number for series: 5


0 1 1 2 3 

In [4]:
# 4. factorial
def fac(n):
    if n<=1:
        return n
    else:
        return n*fac(n-1)
number=int(input("enter the number to factorial:"))
print("factorial of ",number,"is",fac(number))

enter the number to factorial: 5


factorial of  5 is 120


In [8]:
# 5. WAP to check whether the given string is palindrome or not.
string = input("enter the string :")
rev_s=string[::-1]
if rev_s==string:
    print("matched:" , string)
else:
    print("unmatched",string)

enter the string : ere


matched: ere


In [21]:
# 6. WAP to check whether the number is prime or not.
number = int(input("Enter the number to check if it is prime or not: "))
if number > 1:  # Prime numbers are greater than 1
    for i in range(2, number // 2 + 1):  # Include the correct range
        if number % i == 0:
            print("The number is not prime:", number)
            break
    else:
        print("The number is prime:", number)
else:
    print("The number is not prime:", number)  # Handles cases for 0, 1, and negative numbers


Enter the number to check if it is prime or not:  21


The number is not prime: 21


In [30]:
# 7. WAP to print square of the even numbers and cube of the odd numbers in the range from 1 to 100.

even_square = [i**2 for i in range(1, 100) if i % 2 == 0]
odd_square = [i**2 for i in range(1, 100) if i % 2 != 0]

print("Even squares:", even_square)
print("Odd squares:", odd_square)


Even squares: [4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604]
Odd squares: [1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841, 961, 1089, 1225, 1369, 1521, 1681, 1849, 2025, 2209, 2401, 2601, 2809, 3025, 3249, 3481, 3721, 3969, 4225, 4489, 4761, 5041, 5329, 5625, 5929, 6241, 6561, 6889, 7225, 7569, 7921, 8281, 8649, 9025, 9409, 9801]


In [37]:
# 8. WAP to print the square of each numbers in a list using map function.
list1 = [int(input(f'Enter item {i + 1}: ')) for i in range(5)]
square_of_list=list(map(lambda i:i**2,list1))
print(square_of_list)

Enter item 1:  1
Enter item 2:  2
Enter item 3:  3
Enter item 4:  4
Enter item 5:  5


[1, 4, 9, 16, 25]


In [12]:
# 9. print star *
user_number = int(input('Enter the number: '))
# Ensure `number` is always odd
number = user_number + 1 if user_number % 2 == 0 else user_number

# Upper part of the pattern
for i in range(number // 2 + 1):
    print(" " * (number // 2 - i), end="")
    print("*" * (i * 2 + 1))

# Lower part of the pattern
for j in range(number // 2 - 1, -1, -1):
    print(" " * (number // 2 - j), end="")
    print("*" * (j * 2 + 1))


Enter the number:  5


  *
 ***
*****
 ***
  *


In [28]:
# 10.Create a class of student with the attributes.
class student:
    def __init__(self,name,age):
        self.name=name
        self.age=age

obj1=student("prteek",20)


'prteek'

In [1]:
# 1. Write a Python program to print "Hello, World!" in interactive mode.

print("hello, world!")

hello, world!


In [2]:
# 2. Write a program that takes user input for their name and prints a greeting.

name=str(input("enter your name: "))
print(f"good morning!!, {name}")

enter your name:  prteek


good morning!!, prteek


In [3]:
#3.Create a program that demonstrates the use of variables by assigning and printing different data types (e.g., integer, float, string).

integer= int(input("enter the integer:"))
floating_num= float(input("enter the decimal number:"))
string=input("enter the string:") # by default it is str.
print(f"{integer}\n{floating_num}\n{string}")

enter the integer: 82
enter the decimal number: 34.489
enter the string: PRTEEK


82
34.489
PRTEEK


In [6]:
#4. Write a script that takes two numbers as input and prints their sum.

num1=int(input("enter the number:"))
num2=int(input("enter the number:"))
add=num1+num2
print(add)

enter the number: 6
enter the number: 7


13


In [ ]:
#5. Write a program that uses arithmetic operators to perform basic math operations on two user-input numbers.

minus = num1 - num2
mul= num1*num2
divide= num1/num2
floor_division=num1//num2
modulas=num1%5
power=num1**num2
print(f"{minus}\n{add}\n{diivide}\n{floor_division}\n")

In [31]:
# 6. Create a Python script that uses at least three different types of literals (e.g., string,integer, float).
int_number=int(input('enter the number but integer:'))
float_number=float(input('enter the number but float:'))
string=input('enter the string:')
print(f"integer={int_number}\nfloat={float_number}\nstring={string}")

enter the number but integer: 29
enter the number but float: 10
enter the string: prteek


integer=29
float=10.0
string=prteek


In [35]:
# 7. Write a Python script to demonstrate the use of assignment operators.
number=189
print('the integer:',number)
name='prateek'
# number will changed after every operation
print('the string:',name)
number+=10
print('adding in itself:',number)
number-=10
print('subtaract in itself:',number)
number*=2
print('multiply by 2 assing to itself:',number)
number/=2
print('divide by 2 assign to itself:',number)
number%=10
print('taking modulo 10:',number)


the integer: 189
the string: prateek
adding in itself: 199
subtaract in itself: 189
multiply by 2 assing to itself: 378
divide by 2 assign to itself: 189.0
taking modulo 10: 9.0


In [41]:
# 8. Write a program that checks if a given word is a Python keyword.
import keyword
word=input('enter the word:')
if keyword.iskeyword(word):
    print('it is keyword.',word)
else:
    print('it is not keyword.',word)


enter the word: for


it is keyword. for


In [49]:
# 9. Create a program that reads an integer from the user and prints whether it's positive,negative, or zero.
number=int(input('ENTER THE NUMBER:'))

print('positive' if number > 0 else 'negative' if number < 0 else 'zero')  # Output: positive


ENTER THE NUMBER: 0


zero


In [50]:
# 10. Write a program that takes a number as input, converts it to a string, and displays it with a message.
number=int(input('enter the number:'))
str_number=str(number)
print('this is string_number:',str_number)

enter the number: 345


this is string_number: 345


In [51]:
# 11. Write a program to demonstrate the usage of various data types in Python (int, float, bool, string).
number=int(input('ENTER THE NUMBER:'))
float_number=float(input('ENTER THE NUMBER:'))
string=input('ENTER THE STRING:')
boolean=True
print(f'{number},{float_number},{string},{boolean}')

ENTER THE NUMBER: 78
ENTER THE NUMBER: 390
ENTER THE STRING: prateek


78,390.0,prateek,True


In [53]:
# 12.Write a script that stores and prints a list of favorite colors.
fav_color=[input(F'ENTER THE FAVOURITE COLOR {i+1}:') for i in range(5)]
print(fav_color)

ENTER THE FAVOURITE COLOR 1: r
ENTER THE FAVOURITE COLOR 2: g
ENTER THE FAVOURITE COLOR 3: b
ENTER THE FAVOURITE COLOR 4: aurora
ENTER THE FAVOURITE COLOR 5: white


['r', 'g', 'b', 'aurora', 'white']


In [59]:
# 13. Create a program that creates a tuple of 5 numbers and prints the sum of the numbers.
from functools import reduce

numbers = tuple(int(input(f"ENTER THE NUMBER {i+1}: ")) for i in range(5))
addition_of_tuple = reduce(lambda x, y: x + y, numbers)
print(addition_of_tuple)


ENTER THE NUMBER 1:  1
ENTER THE NUMBER 2:  2
ENTER THE NUMBER 3:  3
ENTER THE NUMBER 4:  4
ENTER THE NUMBER 5:  5


15


In [72]:
# 14. Write a program to convert a list into a set and print the vresult.
list_1 = ['a', 'b', 'c', 'c', 'd', 'e', 'a']
set_1 = set(list_1)

print(type(set_1))  # Type of set_1
print(type(list_1))  # Type of list_1
print(set_1, list_1, sep="\n")


<class 'set'>
<class 'list'>
{'a', 'e', 'd', 'b', 'c'}
['a', 'b', 'c', 'c', 'd', 'e', 'a']


In [19]:
# unpacing operator
a = [1, 2]
print(a)  # print as single list 
print(*a) # Expands to: print(1, 2)

[1, 2]
1 2


In [22]:
# 15. Create a dictionary to store student names as keys and their scores as values. Print the dictionary.
result = {str(k): int(v) for k, v in zip(*[iter(input("Enter key-value pairs: ").split())]*2)}
print(result )
# The code takes a single input of space-separated key-value pairs, splits them into a list, and uses zip with two iterators over 
# the list to group alternating elements into key-value pairs, which are then converted to integers and stored in a dictionary.

Enter key-value pairs:  a 10 b 20 c 30 d 44 e 80


{'a': 10, 'b': 20, 'c': 30, 'd': 44, 'e': 80}


In [24]:
# 16. Write a program that demonstrates the immutability of tuples.
tuple1=(1,2,3,4,5)
print(tuple1)
# tuple1[1]=20 # this will through an error.

(1, 2, 3, 4, 5)


In [26]:
# 17. Create a program that adds two lists element-wise and stores the result in a new list.
list_1=[x for x in range(5)]
list_2=[y for y in range(5)]
add_list=list(map(lambda x,y:x+y,list_1,list_2))
print(list_1,list_2,add_list,sep="\n")

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]


In [30]:
# 18. Write a program that accepts user input as a set and performs union and intersection with a predefined set.
predefined_set = {1, 2, 3, 4, 5, 9}

# Taking input from the user and creating a set
user_set = set(int(input(f'Enter a set item{i}: ')) for i in range(7))

# Union and Intersection
union_set = predefined_set | user_set  # Union (all unique elements from both sets)
intersection_set = predefined_set & user_set  # Intersection (common elements)

# Printing the results
print(predefined_set)
print(user_set)
print(union_set)
print(intersection_set)


Enter a set item0:  1
Enter a set item1:  2
Enter a set item2:  3
Enter a set item3:  4
Enter a set item4:  5
Enter a set item5:  6
Enter a set item6:  7


{1, 2, 3, 4, 5, 9}
{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7, 9}
{1, 2, 3, 4, 5}


In [33]:
# 19. Write a Python program to take a string as input and print each character on a new line.
line=input('ENTER THE STRING:')
for i in line:
    print(i)

ENTER THE STRING: my name is ram


m
y
 
n
a
m
e
 
i
s
 
r
a
m


In [34]:
# 20. Create a program that uses string slicing to reverse a given string.
given_string='prateek'
print(given_string[::-1])

keetarp


In [35]:
# 21. Write a script that takes a sentence as input and prints the sentence in all uppercase letters.
sentence =input('enter the sentence:')
print(sentence.upper())

enter the sentence: Hi How Are you


HI HOW ARE YOU


In [39]:
# 22. Write a program that counts the number of vowels in a given string.
sentence = input('Enter the sentence: ')
vowels = ('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U')
count = 0  # Initialize count outside the loop

for i in sentence:
    if i in vowels:  # Check if the character is a vowel
        count += 1  # Increment count for each vowel found
        print(i)  # Print the vowel

print("Total vowels:", count)  # Print the total count of vowels


Enter the sentence:  Hi How Are you


i
o
A
e
o
u
Total vowels: 6


In [40]:
# 23. Create a program that concatenates two strings and prints the result.
string_1='prteek'
string_2='gupta'
print(string_1 + string_2)

prteekgupta


In [43]:
# 24. Write a program to create a list of integers, then print the maximum and minimum values.
numbers=[1,23,45,65,43,55,3,34,32,45,44,65,775,434,34,4455,6,7654,3234,54,3,4,43,4,33,3]
max_number=max(numbers)
min_number=min(numbers)
print("Max number:", max_number)
print("Min number:", min_number)

Max number: 7654
Min number: 1


In [44]:
numbers = [1, 23, 45, 65, 43, 55, 3, 34, 32, 45, 44, 65, 775, 434, 34, 4455, 6, 7654, 3234, 54, 3, 4, 43, 4, 33, 3]

# Initialize max and min with the first number in the list
max_number = numbers[0]
min_number = numbers[0]

# Loop through the list to find max and min
for i in numbers:
    if i > max_number:
        max_number = i  # Update max if current number is greater
    if i < min_number:
        min_number = i  # Update min if current number is smaller

print("Max number:", max_number)
print("Min number:", min_number)


Max number: 7654
Min number: 1


In [52]:
# 25. Write a script to join two lists and print the combined list.
list_1=['p','r','v','g']
list_2=['P','V','A','G']
combined_list=sorted(list_1+list_2) 
list_2.sort()
print(combined_list)
print(list_2)
# sorted() returns a new sorted list, while sort() modifies the list in place and doesn't return anything (hence, no assignment needed).

['A', 'G', 'P', 'V', 'g', 'p', 'r', 'v']
['A', 'G', 'P', 'V']


In [63]:
# 26. Create a program to replicate a list three times and print the result.
list_1='p r t e e k'.split()
print(list_1*3)

['p', 'r', 't', 'e', 'e', 'k', 'p', 'r', 't', 'e', 'e', 'k', 'p', 'r', 't', 'e', 'e', 'k']


In [70]:
# 27. Write a program that takes a list of numbers as input and prints only the even numbers.
numbers = [number for number in range(10)]

# Generate even numbers and convert to list
even_numbers = [even_number for even_number in numbers if even_number % 2 == 0]

print(f"EVEN NUMBERS: {even_numbers}")


EVEN NUMBERS: [0, 2, 4, 6, 8]


In [80]:
# 28. Write a program that creates a tuple of 5 strings and accesses the second element.
# Create a tuple of 5 strings
strings= tuple(input(f"Enter {i}  strings : ") for i in range(5))

# Access the second element
print(f"The tuple is: {strings}")
print(f"The second element is: {strings[1]}")


Enter 0  strings :  j
Enter 1  strings :  h
Enter 2  strings :  g
Enter 3  strings :  l
Enter 4  strings :  p


The tuple is: ('j', 'h', 'g', 'l', 'p')
The second element is: h


In [81]:
# 29. Create a program that joins two tuples and prints the result.
tuple_1=(1,2,3,4,5)
tuple_2=(11,222,33,44,55,32)
print(tuple_1+tuple_2)

(1, 2, 3, 4, 5, 11, 222, 33, 44, 55, 32)


In [82]:
# 30. Write a script that replicates a tuple twice and prints the result.
tuple_1=(1,2,3,4,5)
result=(tuple_1*2)
print(result)

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)


In [93]:
# 31. Write a program that creates a dictionary with three key-value pairs and prints all the keys.
dictionary={str(k): int(v) for k, v in zip(*[iter(input("Enter key-value pairs: ").split())]*2)}
print(dictionary,dictionary.keys(),sep="\n")

Enter key-value pairs:  a 1 b 2 c 3


{'a': 1, 'b': 2, 'c': 3}
dict_keys(['a', 'b', 'c'])


In [3]:
# 32. Create a Python program that creates a set of numbers and prints it.
number_set=set(int(input(f'enter the numbers{i+1}:')) for i in range(5))
print(number_set)

enter the numbers1: 67
enter the numbers2: 88
enter the numbers3: 88
enter the numbers4: 97
enter the numbers5: 56


{88, 97, 56, 67}


In [6]:
# 33. Write a program to convert a list into a frozenset and print it.
lsit_1=list(input(f'enter here {i+1}:') for i in range(5))
print(frozenset(lsit_1))

enter here 1: 2
enter here 2: 2
enter here 3: 4
enter here 4: 3
enter here 5: 1


frozenset({'2', '1', '3', '4'})


In [7]:
# 34. Write a program to demonstrate the use of a set operation (union or intersection) with two sets.
set_1={1,2,3,4,5,4,3,2}
set_2={11,2,3,4,11,22,33,44}
common_items=set_1 & set_2
all_items=set_1|set_2
print(common_items,all_items,sep='\n')

{2, 3, 4}
{1, 2, 3, 4, 5, 33, 11, 44, 22}


In [9]:
# 35. Write a program that uses an `if-else` statement to check if a given number is even or odd.
number=int(input('enter the number:'))
if number%2==0:
    print('even number:',number)
else:
    print('odd number:',number)

enter the number: 555


odd number: 555


In [18]:
# 36. Create a Pandas DataFrame with columns "Name", "Age", and "Score" using sample data. Display the first 5 rows.
import pandas as pd
dict_1={
        'name':['a','b','c','d','e'],
        'age':[23,34,32,22,33],
        'score':[399,333,222,342,324]
}
dataframe=pd.DataFrame(dict_1)
print(dataframe)
dataframe['new']=[1,2,3,4,5]
dataframe

  name  age  score
0    a   23    399
1    b   34    333
2    c   32    222
3    d   22    342
4    e   33    324


name  age  score  new
0    a   23    399    1
1    b   34    333    2
2    c   32    222    3
3    d   22    342    4
4    e   33    324    5

In [22]:
# 37. Load a CSV file into a Pandas DataFrame and print the summary statistics of its numerical columns.
dataframe=pd.read_csv('customer.csv')
print(dataframe)
dataframe.describe()



    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32   

age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [32]:
# 38. Write a program that filters rows in a DataFrame based on a specific condition (e.g., all rows where Age > 20).
# Filter the DataFrame to get ages greater than 20
ages_greater_than_20 = dataframe[dataframe['age'] > 20]['age']
print(ages_greater_than_20)

# Alternatively, using dot notation
print(dataframe[dataframe.age > 20])

0     30
1     68
2     70
3     72
5     31
7     60
8     65
9     74
10    98
11    74
12    51
13    57
15    75
16    59
17    22
19    97
20    57
21    32
23    96
25    57
26    53
27    69
28    48
29    83
30    73
31    22
32    92
33    89
34    86
35    74
36    34
37    94
38    45
39    76
40    39
41    23
42    30
43    27
44    77
45    61
46    64
47    38
48    39
49    25
Name: age, dtype: int64
    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
5    31  Female  Average    School       Yes
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School      

In [36]:
# 39. Create a 3x3 NumPy array with random integers and calculate its transpose.
import numpy as np
import random 


# Create a 3x3 NumPy array with random integers
array = np.random.randint(1, 101, size=(3, 3))  # Random integers between 1 and 100

# Calculate the transpose of the array
transpose_array = array.T

print("Original Array:")
print(array)
print("\nTranspose of the Array:")
print(transpose_array)

Original Array:
[[71 37 17]
 [77 82 19]
 [93 97 29]]

Transpose of the Array:
[[71 77 93]
 [37 82 97]
 [17 19 29]]


In [38]:
# 40. Write a program to create a 1D NumPy array of values from 0 to 10, then replace all even values with -1.

# Create a 1D NumPy array of values from 0 to 10
array = np.array([n for n in range(11)])

# Replace all even values with -1
array[array % 2 == 0] = -1

print("Modified Array:")
print(array)


Modified Array:
[-1  1 -1  3 -1  5 -1  7 -1  9 -1]


In [58]:
# 41. Using a NumPy array, calculate the mean, median, and standard deviation of the values.
array=np.array([int(input()) for i in range(10)])
array_mean=array.mean()
array_median=np.median(array)
array_std_deviation=array.var()
print(array)
print(array_mean)
print(array_median)
print(array_std_deviation)

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10


[ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5
8.25


In [62]:
# 42. Create a Python class called Rectangle with attributes for length and width, and a method to calculate the area of the rectangle.
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

# Create an instance of Rectangle
obj_rect = Rectangle(2, 4)

# Call the area method
print("Area of the rectangle:", obj_rect.area())


Area of the rectangle: 8


In [1]:
# 43. Write a Python class BankAccount with methods to deposit, withdraw, and check the balance. Ensure that withdrawals cannot 
# exceed the balance.
class BankAccount:
    def __init__(self, initial_balance=0):
        self.balance = initial_balance

    # Deposit method to add money to the account
    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited: ${amount}")
        else:
            print("Deposit amount must be greater than 0.")

    # Withdraw method to withdraw money from the account
    def withdraw(self, amount):
        if amount <= 0:
            print("Withdrawal amount must be greater than 0.")
        elif amount > self.balance:
            print("Insufficient balance!")
        else:
            self.balance -= amount
            print(f"Withdrawn: ${amount}")

    # Method to check the balance
    def check_balance(self):
        print(f"Current balance: ${self.balance}")

# Example usage:
account = BankAccount(100)  # Initializing with a balance of $100

account.check_balance()  # Check current balance

account.deposit(50)  # Deposit $50
account.check_balance()  # Check updated balance

account.withdraw(30)  # Withdraw $30
account.check_balance()  # Check updated balance

account.withdraw(150)  # Trying to withdraw more than available balance

Current balance: $100
Deposited: $50
Current balance: $150
Withdrawn: $30
Current balance: $120
Insufficient balance!


In [2]:
# 44. Create an Employee class with name and salary attributes, and a method to give a raise.Demonstrate how to use inheritance
# by creating a Manager subclass.
# Base class: Employee
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    # Method to give a raise to the employee
    def give_raise(self, amount):
        self.salary += amount
        print(f"{self.name} received a raise of ${amount}. New salary: ${self.salary}")

# Subclass: Manager (inherits from Employee)
class Manager(Employee):
    def __init__(self, name, salary, department):
        super().__init__(name, salary)  # Call the parent class constructor
        self.department = department

    # Method to give a raise, but with an additional department-specific raise percentage
    def give_raise(self, amount, raise_percentage=0):
        super().give_raise(amount)  # Call the parent class give_raise method
        if raise_percentage > 0:
            raise_amount = self.salary * (raise_percentage / 100)
            self.salary += raise_amount
            print(f"As a manager of {self.department}, {self.name} also gets a {raise_percentage}% raise. New salary: ${self.salary}")

# Example usage:
# Create an Employee object
employee = Employee("Alice", 50000)
employee.give_raise(2000)

# Create a Manager object
manager = Manager("Bob", 70000, "Sales")
manager.give_raise(3000, 5)

Alice received a raise of $2000. New salary: $52000
Bob received a raise of $3000. New salary: $73000
As a manager of Sales, Bob also gets a 5% raise. New salary: $76650.0


In [2]:
# 45. Write a Python script to read a text file line by line and count the number of lines in the file.
file = open('file.txt', 'r')
count_line = 0

for line in file:
    count_line += 1
    print(line.strip())  # Print the current line

file.close()

print(f"Total lines: {count_line}")


Some content.
i am not well
plz hepl me
how i can help myself.
Total lines: 4


In [6]:
# 46. Write a program that appends text to an existing file without overwriting its current content.

file=open('file.txt','a')
file.write('\ni am good.')
file.close()

file=open('file.txt','r')
a=file.read()
print(a)
file.close()


Some content.
i am not well
plz hepl me 
how i can help myself.i am good.i am good.
i am good.


In [9]:
# 47. Create a script to read a CSV file and print each row in a formatted way.
import pandas as pd

# Read the CSV file
csv_file = pd.read_csv("customer.csv")

# Print each row in a formatted way
for index, row in csv_file.iterrows():
    print(f"Row {index + 1}:")
    for column_name, value in row.items():
        print(f"  {column_name}: {value}")
    print("-" * 20)  # Separator between rows


Row 1:
  age: 30
  gender: Female
  review: Average
  education: School
  purchased: No
--------------------
Row 2:
  age: 68
  gender: Female
  review: Poor
  education: UG
  purchased: No
--------------------
Row 3:
  age: 70
  gender: Female
  review: Good
  education: PG
  purchased: No
--------------------
Row 4:
  age: 72
  gender: Female
  review: Good
  education: PG
  purchased: No
--------------------
Row 5:
  age: 16
  gender: Female
  review: Average
  education: UG
  purchased: No
--------------------
Row 6:
  age: 31
  gender: Female
  review: Average
  education: School
  purchased: Yes
--------------------
Row 7:
  age: 18
  gender: Male
  review: Good
  education: School
  purchased: No
--------------------
Row 8:
  age: 60
  gender: Female
  review: Poor
  education: School
  purchased: Yes
--------------------
Row 9:
  age: 65
  gender: Female
  review: Average
  education: UG
  purchased: No
--------------------
Row 10:
  age: 74
  gender: Male
  review: Good
  educ

In [13]:
# 48. Write a program that asks for two numbers as input and divides the first by the second. Handle any exceptions that may occur
# (e.g.,      ZeroDivisionError, ValueError).
try:
    number_1=int(input("enter the number:"))
    number_2=int(input("enter the number:"))
    division=number_1/number_2
    print(division)
except ZeroDivisionError as e:
    print("number can'tdivide by zero...",e)
except ValueError as e:
    print("enter the the valid value..",e)

enter the number: 5
enter the number: 0


number can'tdivide by zero... division by zero


In [15]:
# 49. Create a function that reads from a file. Handle the FileNotFoundError exception if the file does not exist.
file_name=input('enter the file name with extension:')
try:
    file=open(file_name,'r')
    file.read()
except FileNotFoundError as e:
    print(e)
finally:
    file.close()
    

enter the file name with extension: ac.txt


[Errno 2] No such file or directory: 'ac.txt'


In [24]:
# 50. Write a script that asks the user for a number and calculates its square root.
# Handle cases where the input is not a number or is negative.
try:
    number = float(input("Enter a number: "))
    if number < 0:
        raise ValueError("The number must be non-negative.")
    square_root = number ** 0.5
    print(f"The square root of {number} is {round(square_root, 4)}")
except ValueError as e:
    print(f"Invalid input: {e}")


Enter a number:  cbv


Invalid input: could not convert string to float: 'cbv'
